@startuml
top to bottom direction
class Main
class BodySlam
class DazzlingGleam
class FocusBlast
class CalmMind
class Charm
class DoubleTeam
class Flatter
class PlayNice
class Rest
class Swagger
class Withdraw
class Move
class DamageMove
class PhysicalMove
class StatusMove
class SpecialMove
class Pokemon
class Bounsweet
class Glameow
class Purugly
class Steenee
class TapuBulu
class Tsareena
BodySlam -[plain]-^ PhysicalMove
DazzlingGleam -[plain]-^ SpecialMove
FocusBlast -[plain]-^ SpecialMove
CalmMind -[plain]-^ StatusMove
Charm -[plain]-^ StatusMove
DoubleTeam -[plain]-^ StatusMove
Flatter -[plain]-^ StatusMove
PlayNice -[plain]-^ StatusMove
Rest -[plain]-^ StatusMove
Swagger -[plain]-^ StatusMove
Withdraw -[plain]-^ StatusMove
DamageMove -[plain]-^ Move
StatusMove -[plain]-^ Move
PhysicalMove -[plain]-^ DamageMove
SpecialMove -[plain]-^ DamageMove
Bounsweet -[plain]-^ Pokemon
Glameow -[plain]-^ Pokemon
Purugly -[plain]-^ Pokemon
Steenee -[plain]-^ Pokemon
TapuBulu -[plain]-^ Pokemon
Tsareena -[plain]-^ Pokemon
@enduml
